# Generated by Django 3.0.1 on 2020-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200104_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
